import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f7f5f0",
  },
  shell: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#d8d1c4",
    backgroundColor: "#fbfaf7",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  eyebrow: {
    color: "#6f604a",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  title: {
    color: "#1f1c18",
    fontSize: 24,
    fontWeight: "800",
    marginTop: 2,
  },
  headerSettingsButton: {
    minHeight: 44,
    minWidth: 88,
    borderRadius: 8,
    backgroundColor: "#e5f0eb",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  headerSettingsText: {
    color: "#2f5d50",
    fontSize: 14,
    fontWeight: "800",
  },
  content: {
    padding: 20,
    paddingBottom: 28,
  },
  stack: {
    gap: 14,
  },
  sectionTitle: {
    fontSize: 22,
    lineHeight: 28,
    color: "#1f1c18",
    fontWeight: "800",
  },
  copy: {
    color: "#51493d",
    fontSize: 15,
    lineHeight: 21,
  },
  privacyNote: {
    color: "#6f604a",
    fontSize: 13,
    lineHeight: 18,
  },
  warning: {
    backgroundColor: "#fff3d8",
    borderColor: "#e0bb62",
    borderWidth: StyleSheet.hairlineWidth,
    color: "#5d4210",
    padding: 12,
    borderRadius: 8,
    fontSize: 14,
    lineHeight: 19,
  },
  successBox: {
    backgroundColor: "#e5f0eb",
    borderColor: "#8db3a6",
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 8,
    padding: 12,
    gap: 4,
  },
  successTitle: {
    color: "#2f5d50",
    fontSize: 15,
    fontWeight: "800",
  },
  versionBox: {
    backgroundColor: "#ffffff",
    borderColor: "#d8d1c4",
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 8,
    padding: 14,
    gap: 4,
  },
  versionTitle: {
    color: "#1f1c18",
    fontSize: 16,
    fontWeight: "800",
  },
  primaryButton: {
    backgroundColor: "#2f5d50",
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  secondaryButton: {
    backgroundColor: "#ffffff",
    borderColor: "#b8ad9b",
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 8,
    paddingVertical: 13,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#2f5d50",
    fontSize: 15,
    fontWeight: "800",
  },
  dangerButton: {
    backgroundColor: "#fff7f4",
    borderColor: "#c87a65",
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 8,
    paddingVertical: 13,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  dangerButtonText: {
    color: "#9b3f2d",
    fontSize: 15,
    fontWeight: "800",
  },
  mockImage: {
    height: 220,
    borderRadius: 8,
    backgroundColor: "#ddd6ca",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#b8ad9b",
  },
  mockImageText: {
    color: "#51493d",
    fontWeight: "700",
  },
  queryImageFrame: {
    height: 220,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#ddd6ca",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#b8ad9b",
    position: "relative",
  },
  queryImage: {
    width: "100%",
    height: "100%",
  },
  queryImageLabel: {
    position: "absolute",
    left: 10,
    bottom: 10,
    backgroundColor: "rgba(31, 28, 24, 0.72)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  queryImageLabelText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
  },
  cropFrame: {
    position: "relative",
  },
  cropBox: {
    position: "absolute",
    left: "19%",
    top: "16%",
    width: "62%",
    height: "66%",
    borderWidth: 2,
    borderColor: "#2f5d50",
    borderRadius: 8,
  },
  fieldGroup: {
    gap: 8,
  },
  label: {
    color: "#1f1c18",
    fontWeight: "800",
    fontSize: 14,
  },
  chips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#b8ad9b",
    backgroundColor: "#ffffff",
  },
  chipActive: {
    backgroundColor: "#2f5d50",
    borderColor: "#2f5d50",
  },
  chipText: {
    color: "#51493d",
    fontWeight: "700",
  },
  chipTextActive: {
    color: "#ffffff",
  },
  input: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#b8ad9b",
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
  },
  multilineInput: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  progressStep: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
  },
  progressDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#2f5d50",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d8d1c4",
    padding: 14,
    gap: 8,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  photoRow: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#d8d1c4",
    paddingTop: 10,
    gap: 8,
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  photoThumb: {
    width: 92,
    gap: 4,
  },
  photoThumbImage: {
    width: 92,
    height: 92,
    borderRadius: 8,
    backgroundColor: "#ddd6ca",
  },
  photoThumbLabel: {
    color: "#6f604a",
    fontSize: 12,
    fontWeight: "700",
  },
  rank: {
    color: "#6f604a",
    fontSize: 13,
    fontWeight: "800",
  },
  cardTitle: {
    color: "#1f1c18",
    fontSize: 17,
    fontWeight: "800",
  },
  meta: {
    color: "#6f604a",
    fontSize: 13,
    lineHeight: 18,
  },
  statusPill: {
    color: "#2f5d50",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  badge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: "#e5f0eb",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeText: {
    color: "#2f5d50",
    fontWeight: "800",
    fontSize: 12,
  },
  infoBlock: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d8d1c4",
    padding: 14,
    gap: 6,
  },
  infoTitle: {
    color: "#1f1c18",
    fontSize: 15,
    fontWeight: "800",
  },
  bullet: {
    color: "#51493d",
    fontSize: 14,
    lineHeight: 20,
  },
  noteBox: {
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#b8ad9b",
    backgroundColor: "#fbfaf7",
    padding: 14,
    gap: 4,
  },
  noteTitle: {
    color: "#1f1c18",
    fontSize: 15,
    fontWeight: "800",
  },
  toggleRow: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d8d1c4",
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  toggleLabel: {
    color: "#1f1c18",
    fontSize: 15,
    fontWeight: "700",
    flex: 1,
  },
  tabBar: {
    flexDirection: "row",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#d8d1c4",
    backgroundColor: "#fbfaf7",
    paddingHorizontal: 6,
    paddingTop: 10,
    gap: 4,
  },
  tabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 52,
    paddingVertical: 12,
    borderRadius: 8,
  },
  tabButtonActive: {
    backgroundColor: "#e5f0eb",
  },
  tabText: {
    color: "#6f604a",
    fontSize: 11,
    fontWeight: "800",
  },
  tabTextActive: {
    color: "#2f5d50",
  },
});
